### ISSUE TITLE
有老千

### ISSUE THREAD

**Issue by Sirayuki-zh** [kono-dada/doudizhu#2]
我朋友……[J][J][Q][Q][K][A]……
/jjqqka
会[J][J][Q][Q][K][K][A][A]出去
![2SJH$V$IDZ842O}VY3~` Z1](https://user-images.githubusercontent.com/49672605/134914309-3e9b773e-a794-415d-ada5-714e9357250c.jpg)

**Comment by kono-dada** [comment]
已经修复了，感谢提交issue
